import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '../components/Navbar'
import Howworkshouldwork from '../components/Howworkshouldwork'
import Upyourworkgame from '../components/Upyourworkgame'
import Browsetalent from '../components/Browsetalent'
import Enterprisesuite from '../components/Enterprisesuite'
import Forclients from '../components/Forclients'
import Fortalent from '../components/Fortalent'
import Trustedbyleading from '../components/Trustedbyleading'
import Nasdaq from '../components/Nasdaq'
import Supportukraine from '../components/Supportukraine'
import Topskills from '../components/Topskills'
import Footer from '../components/Footer'
import Whybusinesses from "@/components/Whybusinesses";
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Upwork | The World's Work Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
            <Navbar/>
            <Howworkshouldwork/>
            <Upyourworkgame/>
            <Browsetalent/>
            <Enterprisesuite/>
            <Forclients/>
            <Whybusinesses/>
            <Fortalent/>
            <Trustedbyleading/>
            <Nasdaq/>
            <Supportukraine/>
            <Topskills/>
            <Footer/>
      </main>
    </>
  )
}
